### ISSUE TITLE
setup in local laptop

### ISSUE THREAD

**Issue by micuentadecasa** [aishwaryaprabhat/goku#2]
Hi, anyone has tried to setup this Solution in a local laptop? my idea is to try to run it locally.

Regards.

**Comment by aishwaryaprabhat** [comment]
Hey! You can give it a try with [minikube](https://minikube.sigs.k8s.io/docs/start/) or [kind](https://kind.sigs.k8s.io/). I'll try to find some time and give it a try. The only challenge with local would be the number of cores and RAM but if you can scale down the requirements and limits of each component or only install components selectively, it should work!

**Comment by micuentadecasa** [comment]
Many thanks @aishwaryaprabhat , I will try it too.

**Comment by aishwaryaprabhat** [comment]
If you figure something out that others could benefit from, kindly PR to the repo!
